const titles={dashboard:'Dashboard',rapport:'Rapport Schrijver',excel:'Excel Assistent',beng:'BENG Checker',normen:'Norm Monitor',kennis:'Kennisbank'};
function show(id,el){
  document.querySelectorAll('.page').forEach(p=>p.classList.remove('active'));
  document.querySelectorAll('.nav-item').forEach(n=>n.classList.remove('active'));
  document.getElementById('page-'+id).classList.add('active');
  if(el)el.classList.add('active');
  document.getElementById('ptitle').textContent=titles[id]||id;
  if(id==='kennis')searchKB();
}
function selRT(el){document.querySelectorAll('.rt-btn').forEach(b=>b.classList.remove('sel'));el.classList.add('sel');}
function genRapport(){
  const bar=document.getElementById('rpbar'),lbl=document.getElementById('rp-lbl'),prog=document.getElementById('rp-prog'),out=document.getElementById('rp-out'),acts=document.getElementById('rp-acts');
  prog.style.display='block';acts.style.display='none';out.innerHTML='<span style="color:var(--soft)">Rapport wordt opgesteld...</span>';
  const steps=[[15,'Projectgegevens verwerken...'],[35,'VIAC templates laden...'],[55,'Paris Proof normen toepassen...'],[75,'Installatieschema opstellen...'],[92,'Rapport opmaken...'],[100,'Rapport gereed!']];
  let i=0;const run=()=>{if(i<steps.length){bar.style.width=steps[i][0]+'%';lbl.textContent=steps[i][1];i++;setTimeout(run,450);}else{prog.style.display='none';acts.style.display='flex';acts.innerHTML='<button class="btn btn-primary btn-sm">⬇ Download .docx</button><button class="btn btn-outline btn-sm">✏ Bewerk</button>';out.innerHTML=`<strong style="color:var(--teal);font-family:'Playfair Display',serif;">BENG Rapportage — Kantoor Papendorp fase 2</strong><br><br><strong>Opdrachtgever:</strong> Syntrus Achmea Real Estate<br><strong>Adviseur:</strong> VIAC Adviseurs BV · 21 april 2026<br><br><strong>1. Projectomschrijving</strong><br>Transformatie van het kantoorgebouw Papendorp fase 2 naar een Paris Proof gebouw. BVO: 2.840 m². Volledige renovatie W/E installaties.<br><br><strong>2. Installatieconcept</strong><br>Lucht-water warmtepomp (COP 4,2) + PV 72 kWp + WTW ventilatie η=88%. Gasaansluiting verwijderd.<br><br><strong>3. BENG Indicatoren</strong><br>• BENG 1: <strong style="color:var(--green)">42 kWh/m²/jr ✓</strong> (eis ≤50)<br>• BENG 2: <strong style="color:var(--green)">27 kWh/m²/jr ✓</strong> (eis ≤30 na 2027)<br>• BENG 3: <strong style="color:var(--green)">68% ✓</strong> (eis ≥50%)<br><br><em style="color:var(--soft);">Opgesteld door VIAC Digitaal Platform · NEN 7120 + Paris Proof 2030</em>`;}};run();
}
function loadXLS(){
  document.getElementById('xls-body').innerHTML=`<div style="margin-bottom:10px;font-size:12px;color:var(--soft);">📂 warmteverliesberekening.xlsx geladen</div><div class="xls-preview"><div class="xrow xhead"><div class="xcell">Bouwdeel</div><div class="xcell">Opp. m²</div><div class="xcell">U-waarde</div><div class="xcell">Temp.∆</div><div class="xcell">Verlies W</div></div><div class="xrow"><div class="xcell">Gevel noord</div><div class="xcell">184</div><div class="xcell">0.21</div><div class="xcell">22</div><div class="xcell">849</div></div><div class="xrow"><div class="xcell">Gevel oost</div><div class="xcell">96</div><div class="xcell">0.21</div><div class="xcell">22</div><div class="xcell">443</div></div><div class="xrow"><div class="xcell">Dak</div><div class="xcell">710</div><div class="xcell" style="color:var(--amber);font-weight:600;">?</div><div class="xcell">22</div><div class="xcell" style="color:var(--amber);">—</div></div><div class="xrow"><div class="xcell">Begane grond</div><div class="xcell">710</div><div class="xcell" style="color:var(--amber);font-weight:600;">?</div><div class="xcell">10</div><div class="xcell" style="color:var(--amber);">—</div></div><div class="xrow"><div class="xcell">Glas totaal</div><div class="xcell">340</div><div class="xcell">0.70</div><div class="xcell">22</div><div class="xcell">5.236</div></div></div><div style="margin-bottom:10px;"><span class="ai-chip">✦ 2 ontbrekende waarden gedetecteerd</span></div><button class="btn btn-primary btn-sm" onclick="procXLS()">✦ Verwerk automatisch</button>`;
}
function procXLS(){
  const b=document.getElementById('xls-body');b.innerHTML='<div class="prog-wrap"><div class="prog-bar" id="xpbar" style="width:0%"></div></div><div style="font-size:11px;color:var(--mid);margin-top:4px;">NEN 1068 waarden opzoeken...</div>';
  let w=0;const iv=setInterval(()=>{w+=8;document.getElementById('xpbar').style.width=w+'%';if(w>=100){clearInterval(iv);b.innerHTML=`<div style="margin-bottom:8px;"><span class="ai-chip">✦ 2 waarden ingevuld · totaal berekend</span></div><div class="xls-preview"><div class="xrow xhead"><div class="xcell">Bouwdeel</div><div class="xcell">Opp. m²</div><div class="xcell">U-waarde</div><div class="xcell">Temp.∆</div><div class="xcell">Verlies W</div></div><div class="xrow"><div class="xcell">Gevel noord</div><div class="xcell">184</div><div class="xcell">0.21</div><div class="xcell">22</div><div class="xcell">849</div></div><div class="xrow"><div class="xcell">Gevel oost</div><div class="xcell">96</div><div class="xcell">0.21</div><div class="xcell">22</div><div class="xcell">443</div></div><div class="xrow"><div class="xcell">Dak</div><div class="xcell">710</div><div class="xcell xai">0.20 ✦</div><div class="xcell">22</div><div class="xcell xai">3.124 ✦</div></div><div class="xrow"><div class="xcell">Begane grond</div><div class="xcell">710</div><div class="xcell xai">0.25 ✦</div><div class="xcell">10</div><div class="xcell xai">1.775 ✦</div></div><div class="xrow"><div class="xcell">Glas totaal</div><div class="xcell">340</div><div class="xcell">0.70</div><div class="xcell">22</div><div class="xcell">5.236</div></div><div class="xrow" style="background:var(--teal-light);font-weight:700;"><div class="xcell">TOTAAL</div><div class="xcell">—</div><div class="xcell">—</div><div class="xcell">—</div><div class="xcell xai">11.427 W ✦</div></div></div><div style="background:var(--teal-light);border-radius:8px;padding:12px;font-size:12px;color:var(--teal);margin-top:8px;"><strong>Conclusie:</strong> Transmissieverlies 11,4 kW. Voldoet aan BENG eis. <strong style="color:var(--green);">✓ BENG 1 gehaald.</strong></div><div style="margin-top:10px;display:flex;gap:8px;"><button class="btn btn-primary btn-sm">⬇ Download Excel</button><button class="btn btn-outline btn-sm">📄 Naar rapport</button></div>`;}},100);
}
function checkBENG(){
  const b=document.getElementById('beng-body');b.innerHTML='<div class="prog-wrap"><div class="prog-bar" id="bpbar" style="width:0%"></div></div>';
  let w=0;const iv=setInterval(()=>{w+=10;document.getElementById('bpbar').style.width=w+'%';if(w>=100){clearInterval(iv);b.innerHTML=`<div class="brc"><div class="brow"><div style="font-size:12px;color:var(--mid)">BENG 1 — Energiebehoefte</div><div style="font-size:13px;font-weight:700;color:var(--green)">42 kWh/m²/jr ✓</div></div><div class="brow"><div style="font-size:11px;color:var(--soft)">Eis (kantoor)</div><div style="font-size:11px;color:var(--mid)">≤ 50 kWh/m²/jr</div></div></div><div class="brc"><div class="brow"><div style="font-size:12px;color:var(--mid)">BENG 2 — Primair fossiel</div><div style="font-size:13px;font-weight:700;color:var(--green)">27 kWh/m²/jr ✓</div></div><div class="brow"><div style="font-size:11px;color:var(--soft)">Eis vanaf 2027</div><div style="font-size:11px;color:var(--mid)">≤ 30 kWh/m²/jr</div></div></div><div class="brc"><div class="brow"><div style="font-size:12px;color:var(--mid)">BENG 3 — Hernieuwbaar</div><div style="font-size:13px;font-weight:700;color:var(--green)">68% ✓</div></div><div class="brow"><div style="font-size:11px;color:var(--soft)">Eis</div><div style="font-size:11px;color:var(--mid)">≥ 50%</div></div></div><div style="background:#E3F5EC;border-radius:8px;padding:12px;margin-top:8px;"><div style="font-size:13px;font-weight:700;color:var(--green);">✓ Alle BENG indicatoren gehaald</div><div style="font-size:11px;color:var(--mid);margin-top:4px;">Kwalificeert voor Paris Proof 2030. BENG 2 heeft 10% marge boven de 2027 eis.</div></div><div style="margin-top:10px;display:flex;gap:8px;"><button class="btn btn-primary btn-sm">📄 Genereer BENG rapport</button><button class="btn btn-outline btn-sm">⬇ PDF</button></div>`;}},100);
}
const kbData=[
  {title:'Warmtepomp renovatie UMCU fase 1',meta:'Zorg · 2023 · 12.400 m² · Utrecht',snip:'Lucht-water warmtepompen in 6 vleugels. COP gemeten 4.1. Aardgasvrij behaald. Projectduur 14 maanden.',score:97},
  {title:'WKO-systeem Antonius Ziekenhuis Nieuwegein',meta:'Zorg · 2022 · 28.000 m² · Nieuwegein',snip:'Warmte-koude opslag met absorptiekoeling. Energiebesparing 62% t.o.v. referentie. Paris Proof gehaald.',score:91},
  {title:'Renovatie warmtesysteem woonzorgcentrum Zeist',meta:'Zorg · 2024 · 4.200 m² · Zeist',snip:'Hybride warmtepomp systeem. Gasverbruik min 78%. BMS integratie voor real-time monitoring.',score:88},
  {title:'Duurzame installaties Meander MC',meta:'Zorg · 2021 · 45.000 m² · Amersfoort',snip:'Totaalrenovatie W/E. WKO + warmtepomp. BREEAM Excellent. CO₂ reductie 71%.',score:84},
];
function searchKB(){
  const q=document.getElementById('kb-q').value;
  document.getElementById('kb-meta').textContent=kbData.length+` resultaten voor "${q}" — gesorteerd op relevantie`;
  document.getElementById('kb-results').innerHTML=kbData.map(k=>`<div class="kb-item"><span class="match">${k.score}% match</span><div class="kb-title">${k.title}</div><div class="kb-meta">${k.meta}</div><div class="kb-snip">${k.snip}</div></div>`).join('');
}
