const titles={dashboard:'Dashboard',rapport:'Rapport Schrijver',excel:'Excel Assistent',beng:'BENG Checker',normen:'Norm Monitor',kennis:'Kennisbank'};
function show(id,el){
  document.querySelectorAll('.page').forEach(p=>p.classList.remove('active'));
  document.querySelectorAll('.nav-item').forEach(n=>n.classList.remove('active'));
  document.getElementById('page-'+id).classList.add('active');
  if(el)el.classList.add('active');
  document.getElementById('ptitle').textContent=titles[id]||id;
  if(id==='kennis')searchKB();
}
function selRT(el){document.querySelectorAll('.rt-btn').forEach(b=>b.classList.remove('sel'));el.classList.add('sel');}
function genRapport(){
  const bar=document.getElementById('rpbar'),lbl=document.getElementById('rp-lbl'),prog=document.getElementById('rp-prog'),out=document.getElementById('rp-out'),acts=document.getElementById('rp-acts');
  prog.style.display='block';acts.style.display='none';out.innerHTML='<span style="color:var(--soft)">Rapport wordt opgesteld...</span>';
  const steps=[[12,'Projectgegevens verwerken...'],[28,'Feniks-templates laden...'],[46,'NEN-EN 12354 normen toepassen...'],[63,'Geluidsisolatie waarden berekenen...'],[80,'Aanbevelingen formuleren...'],[95,'Rapport opmaken...'],[100,'Rapport gereed!']];
  let i=0;const run=()=>{if(i<steps.length){bar.style.width=steps[i][0]+'%';lbl.textContent=steps[i][1];i++;setTimeout(run,420);}else{prog.style.display='none';acts.style.display='flex';acts.innerHTML='<button class="btn btn-primary btn-sm">⬇ Download .docx</button><button class="btn btn-outline btn-sm">✏ Bewerk</button>';out.innerHTML=`<strong style="color:var(--accent);font-family:'Crimson Text',serif;font-size:16px;">Akoestisch Rapport — Appartementen Lombok Utrecht</strong><br><br><strong style="color:var(--mid);">Opdrachtgever:</strong> <span style="color:var(--text);">Heijmans Wonen BV</span><br><strong style="color:var(--mid);">Adviseur:</strong> <span style="color:var(--text);">Feniks Installatie-adviseurs · H. Tromp · 21 april 2026</span><br><br><strong style="color:var(--text);">1. Projectomschrijving</strong><br><span style="color:var(--mid);">Renovatie van 48 bestaande appartementen te Utrecht-Lombok. Aanleiding: klachten over geluidshinder tussen woningen. Scope: analyse bestaande situatie, ontwerp verbetermaatregelen en begeleiding uitvoering.</span><br><br><strong style="color:var(--text);">2. Bestaande situatie</strong><br><span style="color:var(--mid);">Veldmeting conform NEN-EN ISO 16283-1 uitgevoerd op 8 representatieve scheidingsvloeren. Gemeten DnT,A,k gemiddeld <strong style="color:var(--red);">46 dB</strong> — niet voldoend aan Bbl eis van 52 dB.</span><br><br><strong style="color:var(--text);">3. Verbetermaatregelen</strong><br><span style="color:var(--mid);">• Drijvende dekvloer 80mm (betonkern + isolatie) → verwachte verbetering +11 dB<br>• Plafondvering woningscheidende wanden → +6 dB<br>• Akoestische dichte kieren- en naaddichting installaties</span><br><br><strong style="color:var(--text);">4. Verwacht resultaat</strong><br><span style="color:var(--mid);">Na uitvoering: DnT,A,k ≥ <strong style="color:var(--green);">57 dB ✓</strong> — voldoet ruimschoots aan Bbl eis én nieuwe Bbl-norm 2027 (≥55 dB).</span><br><br><em style="color:var(--soft);font-size:11px;">Gegenereerd door Feniks Digitaal Platform · NEN-EN 12354-1 + Bbl 2026 · 40 jaar bouwfysische expertise</em>`;}};run();
}
function loadXLS(){
  document.getElementById('xls-body').innerHTML=`<div style="margin-bottom:10px;font-size:12px;color:var(--soft);">📂 geluidsisolatie_berekening.xlsx geladen</div><div class="xls-preview"><div class="xrow xhead"><div class="xcell">Scheidingsconstructie</div><div class="xcell">Opp. m²</div><div class="xcell">Rw (dB)</div><div class="xcell">Correctie C</div><div class="xcell">DnT,A,k</div></div><div class="xrow"><div class="xcell">Woningscheidende vloer</div><div class="xcell">62</div><div class="xcell">48</div><div class="xcell">-2</div><div class="xcell">46</div></div><div class="xrow"><div class="xcell">Woningscheidende wand</div><div class="xcell">28</div><div class="xcell">52</div><div class="xcell">-1</div><div class="xcell">51</div></div><div class="xrow"><div class="xcell">Drijvende dekvloer</div><div class="xcell">62</div><div class="xcell xai" style="color:var(--amber);font-weight:700;">?</div><div class="xcell">-2</div><div class="xcell" style="color:var(--amber);">—</div></div><div class="xrow"><div class="xcell">Leidinggeluiddempende vloer</div><div class="xcell">12</div><div class="xcell xai" style="color:var(--amber);font-weight:700;">?</div><div class="xcell">0</div><div class="xcell" style="color:var(--amber);">—</div></div><div class="xrow"><div class="xcell">Buitengevel</div><div class="xcell">18</div><div class="xcell">35</div><div class="xcell">-3</div><div class="xcell">32</div></div></div><div style="margin-bottom:10px;"><span class="ai-chip">🔥 Gedetecteerd: 2 ontbrekende Rw-waarden</span></div><button class="btn btn-primary btn-sm" onclick="procXLS()">🔥 Verwerk automatisch</button>`;
}
function procXLS(){
  const b=document.getElementById('xls-body');b.innerHTML='<div class="prog-wrap"><div class="prog-bar" id="xpbar" style="width:0%"></div></div><div style="font-size:11px;color:var(--mid);margin-top:4px;">NEN-EN 12354 waarden opzoeken...</div>';
  let w=0;const iv=setInterval(()=>{w+=8;document.getElementById('xpbar').style.width=w+'%';if(w>=100){clearInterval(iv);b.innerHTML=`<div style="margin-bottom:8px;"><span class="ai-chip">🔥 2 waarden ingevuld · totaal berekend</span></div><div class="xls-preview"><div class="xrow xhead"><div class="xcell">Scheidingsconstructie</div><div class="xcell">Opp. m²</div><div class="xcell">Rw (dB)</div><div class="xcell">Correctie C</div><div class="xcell">DnT,A,k</div></div><div class="xrow"><div class="xcell">Woningscheidende vloer</div><div class="xcell">62</div><div class="xcell">48</div><div class="xcell">-2</div><div class="xcell">46</div></div><div class="xrow"><div class="xcell">Woningscheidende wand</div><div class="xcell">28</div><div class="xcell">52</div><div class="xcell">-1</div><div class="xcell">51</div></div><div class="xrow"><div class="xcell">Drijvende dekvloer</div><div class="xcell">62</div><div class="xcell xai">59 ✦</div><div class="xcell">-2</div><div class="xcell xai">57 ✦</div></div><div class="xrow"><div class="xcell">Leidinggeluiddempende vloer</div><div class="xcell">12</div><div class="xcell xai">45 ✦</div><div class="xcell">0</div><div class="xcell xai">45 ✦</div></div><div class="xrow"><div class="xcell">Buitengevel</div><div class="xcell">18</div><div class="xcell">35</div><div class="xcell">-3</div><div class="xcell">32</div></div><div class="xrow" style="background:rgba(196,80,10,.12);font-weight:700;"><div class="xcell" style="color:var(--accent);">GEWOGEN RESULTAAT</div><div class="xcell">—</div><div class="xcell">—</div><div class="xcell">—</div><div class="xcell xai">DnT,A,k 53 dB ✦</div></div></div><div style="background:rgba(76,175,125,.1);border:1px solid rgba(76,175,125,.2);border-radius:8px;padding:12px;font-size:12px;color:var(--green);margin-top:8px;"><strong>Conclusie:</strong> Gecombineerde geluidsisolatie DnT,A,k = 53 dB. <strong>Voldoet aan huidige Bbl eis ≥52 dB ✓.</strong> Let op: bij renovatie ná 2027 is eis ≥55 dB — aanvullende maatregelen nodig.</div><div style="margin-top:10px;display:flex;gap:8px;"><button class="btn btn-primary btn-sm">⬇ Download Excel</button><button class="btn btn-outline btn-sm">📄 Naar rapport</button></div>`;}},100);
}
function checkBENG(){
  const b=document.getElementById('beng-body');b.innerHTML='<div class="prog-wrap"><div class="prog-bar" id="bpbar" style="width:0%"></div></div>';
  let w=0;const iv=setInterval(()=>{w+=10;document.getElementById('bpbar').style.width=w+'%';if(w>=100){clearInterval(iv);b.innerHTML=`<div class="brc"><div class="brow"><div style="font-size:12px;color:var(--mid)">BENG 1 — Energiebehoefte</div><div style="font-size:13px;font-weight:700;color:var(--green)">68 kWh/m²/jr ✓</div></div><div class="brow"><div style="font-size:11px;color:var(--soft)">Eis (woning, renovatie)</div><div style="font-size:11px;color:var(--mid)">≤ 75 kWh/m²/jr</div></div></div><div class="brc"><div class="brow"><div style="font-size:12px;color:var(--mid)">BENG 2 — Primair fossiel</div><div style="font-size:13px;font-weight:700;color:var(--amber)">28 kWh/m²/jr ⚠</div></div><div class="brow"><div style="font-size:11px;color:var(--soft)">Eis huidig / eis 2026</div><div style="font-size:11px;color:var(--mid)">≤30 / ≤25 per 1 jul 2026</div></div></div><div class="brc"><div class="brow"><div style="font-size:12px;color:var(--mid)">BENG 3 — Hernieuwbaar</div><div style="font-size:13px;font-weight:700;color:var(--green)">61% ✓</div></div><div class="brow"><div style="font-size:11px;color:var(--soft)">Eis woning</div><div style="font-size:11px;color:var(--mid)">≥ 50%</div></div></div><div style="background:rgba(229,166,35,.12);border:1px solid rgba(229,166,35,.25);border-radius:8px;padding:12px;margin-top:8px;"><div style="font-size:13px;font-weight:700;color:var(--amber);">⚠ Let op: BENG 2 krappe marge</div><div style="font-size:11px;color:var(--mid);margin-top:4px;">Huidig ontwerp voldoet aan huidige eis (≤30). Maar per 1 juli 2026 geldt eis ≤25 kWh/m²/jr. Aanbeveling: extra PV of COP verbeteren van 3,8 naar 4,2.</div></div><div style="margin-top:10px;display:flex;gap:8px;"><button class="btn btn-primary btn-sm">📄 Genereer BENG rapport</button><button class="btn btn-outline btn-sm">⬇ PDF</button></div>`;}},100);
}
const kbData=[
  {title:'Geluidsisolatie renovatie Transwijk-flats Utrecht',meta:'Akoestiek · 2022 · 72 appartementen · Utrecht',snip:'Volledige akoestische renovatie woningscheidende vloeren en wanden. DnT,A,k verbeterd van 44 naar 58 dB. NEN-EN 12354 conform.',score:98},
  {title:'Installatieadvies bestaande bouw Zeist',meta:'Bestaande bouw · 2023 · 3.400 m² · Zeist',snip:'Diagnose storingen CV-installatie 30 jaar oud gebouw. Leiding corrosie, ventielproblemen. Gefaseerde vervanging zonder sloopoverlast.',score:94},
  {title:'BIM model validatie renovatie Nieuwegein',meta:'BIM · 2024 · 8.200 m² · Nieuwegein',snip:'Clash-detectie W/E installaties in Revit BIM model. 147 clashes gedetecteerd en opgelost voor uitvoering. €180k faalkosten voorkomen.',score:89},
  {title:'Directievoering nieuwbouw woningen De Meern',meta:'Directievoering · 2021 · 64 woningen · Utrecht',snip:'Bouwtoezicht W/E installaties gedurende 18 maanden. Oplevering conform planning. 0 gebreken bij eindoplevering.',score:85},
];
function searchKB(){
  const q=document.getElementById('kb-q').value;
  document.getElementById('kb-meta').textContent=kbData.length+` resultaten voor "${q}" — gesorteerd op relevantie`;
  document.getElementById('kb-results').innerHTML=kbData.map(k=>`<div class="kb-item"><span class="match">${k.score}% match</span><div class="kb-title">${k.title}</div><div class="kb-meta">${k.meta}</div><div class="kb-snip">${k.snip}</div></div>`).join('');
}
